apiVersion: batch/v1
kind: Job
metadata:
  name: fail-script-job
  namespace: rbac-lab
spec:
  backoffLimit: 3
  template:
    spec:
      restartPolicy: Never
      containers:
      - name: worker
        image: busybox:1.37
        command:
        - sh
        - -c
        - |
          echo "Starting failing task..."
          sleep 2
          echo "Error: something went wrong"
          exit 1
