apiVersion: batch/v1
kind: Job
metadata:
  name: tamirtest
  namespace: rbac-lab
spec:
  ttlSecondsAfterFinished: 30
  backoffLimit: 2
  completions: 3
  parallelism: 1
  template:
    spec:
      restartPolicy: Never
      containers:
      - name: tamirtest
        image: busybox:1.37
        command: ["/bin/sh", "-c", "echo 'Hello, World!'; sleep 20"]
        imagePullPolicy: IfNotPresent
