apiVersion: v1
kind: Service
metadata:
  name: api-nodeport
  namespace: rbac-lab
spec:
  type: NodePort
  selector:
    app: store
    tier: backend
  ports:
  - port: 80
    targetPort: 80
    nodePort: 30980
    protocol: TCP
    name: http
